CherryPy        - 3.2.2        - active 
Django          - 1.4          - active 
Python          - 2.7.2        - active development (/Users/josh/.pythonbrew/pythons/Python-2.7.2/lib/python2.7/lib-dynload)
South           - 0.7.5        - active 
amqplib         - 1.0.2        - active 
anyjson         - 0.3.1        - active 
argparse        - 1.2.1        - active 
bambu-tools     - 1.8          - active 
celery          - 2.5.3        - active 
certifi         - 0.0.8        - active 
chardet         - 1.0.1        - active 
colorama        - 0.2.4        - active 
django-audit    - 1.0b3        - active 
django-celery   - 2.5.5        - active 
django-dajax    - 0.8.4        - active 
django-dajaxice - 0.2          - active 
django-durationfield - 0.3.3        - active 
django-extensions - 0.8          - active 
django-mockups  - 0.4.8        - active 
django-notes    - 0.2.2        - active 
django-picklefield - 0.2.1        - active 
django-pyvows   - 0.6.1        - active 
gevent          - 0.13.7       - active 
googleappsauth  - 1.03         - active 
greenlet        - 0.3.4        - active 
gunicorn        - 0.14.3       - active 
httplib2        - 0.7.4        - active 
kombu           - 2.1.8        - active 
lxml            - 2.3.4        - active 
oauthlib        - 0.1.3        - active 
pip             - 1.1          - active 
pyVows          - 1.0.0        - active 
pyasn1          - 0.1.3        - active 
pymongo         - 2.2          - active 
python-dateutil - 1.5          - active 
requests        - 0.12.1       - active 
rsa             - 3.0.1        - active 
setuptools      - 0.6c11       - active 
wsgiref         - 0.1.2        - active development (/Users/josh/.pythonbrew/pythons/Python-2.7.2/lib/python2.7)
yolk            - 0.4.3        - active 
